import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { buildScene } from './scene.js';
import { animateZombie, createZombieModel, ZOMBIE_TYPES } from './zombie.js';
import { initAudio, isMuted, setSpraying, sfx, toggleMute } from './audio.js';
import { advanceEnemy, applyPowerUp, applyWater, clamp, MAX_AIM_PITCH, MAX_AIM_YAW, MIN_AIM_PITCH, POWER_UP_TYPES, relativeAngle, resolveContact, stepAim, tickBoosts } from './mechanics.js';
const EYE_HEIGHT = 2.05, GYRO_SENSITIVITY = .5, AIM_SMOOTHING = 3, AIM_MAX_SPEED = .9;
const POWER_UPS = { water: { label: '超級水柱', color: 0x3fd8ff }, bomb: { label: '冰凍炸彈', color: 0xb8f6ff }, heal: { label: '補血 +30', color: 0xff6f91 }, slow: { label: '殭屍變慢', color: 0xc38bff } };

const canvas = document.querySelector('#game');
const ui = { mute: document.querySelector('#muteButton'), powerUp: document.querySelector('#powerUp'), panel: document.querySelector('#startPanel'), start: document.querySelector('#startButton'), healthBar: document.querySelector('#healthBar'), healthText: document.querySelector('#healthText'), score: document.querySelector('#score'), message: document.querySelector('#message'), flash: document.querySelector('#hitFlash'), meter: document.querySelector('#freezeMeter'), meterFill: document.querySelector('#freezeMeter i'), crosshair: document.querySelector('.crosshair') };
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, powerPreference: 'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.15;
const scene = new THREE.Scene(); scene.background = new THREE.Color(0x0b1a26); scene.fog = new THREE.FogExp2(0x1a2240, 0.018);
const camera = new THREE.PerspectiveCamera(72, innerWidth / innerHeight, .05, 120); camera.position.set(0, EYE_HEIGHT, 4.8); camera.rotation.order = 'YXZ'; scene.add(camera);
scene.add(new THREE.HemisphereLight(0x9fb8ff, 0x2a2a3a, 2.1));
const moon = new THREE.DirectionalLight(0xb9eaff, 3.4); moon.position.set(-8, 16, 2); moon.castShadow = true; moon.shadow.mapSize.set(1024, 1024); moon.shadow.camera.left = -20; moon.shadow.camera.right = 20; moon.shadow.camera.top = 20; moon.shadow.camera.bottom = -30; moon.shadow.camera.far = 60; scene.add(moon);
const state = { running: false, spraying: false, health: 100, score: 0, wave: 0, enemies: [], particles: [], spawnTimer: 0, yaw: 0, pitch: 0, baseYaw: null, basePitch: null, groanTimer: 3, dragX: 0, dragY: 0, dragging: false, items: [], itemTimer: 0, boosts: { water: 0, slow: 0 } };
const raycaster = new THREE.Raycaster(), center = new THREE.Vector2(0, 0), clock = new THREE.Clock();

function createBlaster() {
  const gun = new THREE.Group(), blue = new THREE.MeshStandardMaterial({ color: 0x21bfd5, roughness: .35, metalness: .15 }), yellow = new THREE.MeshStandardMaterial({ color: 0xffd849, roughness: .45 });
  const body = new THREE.Mesh(new THREE.CylinderGeometry(.16, .24, 1.15, 16), blue); body.rotation.x = Math.PI / 2; body.position.z = -.4; gun.add(body);
  const tank = new THREE.Mesh(new THREE.SphereGeometry(.3, 16, 12), new THREE.MeshPhysicalMaterial({ color: 0x5feeff, transparent: true, opacity: .66, transmission: .25 })); tank.scale.set(1, 1.25, 1); tank.position.set(0, .08, .02); gun.add(tank);
  const flower = new THREE.Group(); flower.position.z = -.98; for (let i = 0; i < 8; i++) { const petal = new THREE.Mesh(new THREE.SphereGeometry(.11, 10, 8), yellow); const a = i * Math.PI / 4; petal.position.set(Math.cos(a) * .17, Math.sin(a) * .17, 0); petal.scale.set(1.25, .7, .45); flower.add(petal); } const nozzle = new THREE.Mesh(new THREE.CylinderGeometry(.1, .12, .12, 14), blue); nozzle.rotation.x = Math.PI / 2; flower.add(nozzle); gun.add(flower);
  gun.position.set(.42, -.5, -1.05); gun.rotation.set(-.06, -.06, 0); camera.add(gun); return { gun, flower };
}

function createZombie(type = 'normal') {
  const cfg = ZOMBIE_TYPES[type], model = createZombieModel(type), group = model.root; group.userData.enemyRoot = group;
  const distance = 18 + Math.random() * 18, angle = (Math.random() - .5) * 1.25; group.position.set(Math.sin(angle) * distance, 0, camera.position.z - Math.cos(angle) * distance);
  Object.assign(group.userData, { type, alive: true, freeze: 0, freezeRate: cfg.rate, speed: cfg.speed, damage: cfg.damage, distance, points: cfg.points, phase: Math.random() * 6, body: model.body, head: model.head, limbs: model.limbs, parts: model.parts, baseColors: model.baseColors }); scene.add(group); state.enemies.push(group); return group;
}

const updateScene = buildScene(scene); const blaster = createBlaster();
function spawnWave() { state.wave += 1; const count = Math.min(2 + state.wave, 8); for (let i = 0; i < count; i++) createZombie(state.wave > 2 && i % 4 === 0 ? 'tank' : state.wave > 1 && i % 3 === 0 ? 'fast' : 'normal'); announce(`第 ${state.wave} 波來了`); sfx.wave(); }
function updateEnemy(enemy, dt, elapsed) {
  const data = enemy.userData; if (!data.alive) return; const toPlayer = new THREE.Vector3(camera.position.x - enemy.position.x, 0, camera.position.z - enemy.position.z); data.distance = toPlayer.length(); advanceEnemy(data, dt); if (data.freeze < 100) enemy.position.addScaledVector(toPlayer.normalize(), data.speed * (1 - clamp(data.freeze / 125, 0, .8)) * dt); enemy.lookAt(camera.position.x, enemy.position.y, camera.position.z);
  animateZombie(data, elapsed, data.freeze);
  const contact = resolveContact(state.health, data, 1.35); if (contact.hit) { state.health = contact.health; scene.remove(enemy); hitPlayer(); updateHud(); if (state.health <= 0) gameOver(); }
}
function findEnemyRoot(object) { let current = object; while (current && !current.userData.enemyRoot) current = current.parent; return current?.userData.enemyRoot || null; }
function aimOffsets() { const spread = state.boosts.water > 0 ? .2 : .13, aspect = camera.aspect; const offsets = [[0, 0]]; for (let i = 0; i < 8; i++) { const a = i * Math.PI / 4; offsets.push([Math.cos(a) * spread / aspect, Math.sin(a) * spread]); } return offsets; }
function castAim(objects) { let best = null; for (const [x, y] of aimOffsets()) { center.set(x, y); raycaster.setFromCamera(center, camera); const hit = raycaster.intersectObjects(objects, true)[0]; if (hit && (!best || hit.distance < best.distance)) best = hit; if (best && x === 0 && y === 0) break; } center.set(0, 0); return best; }
function targetEnemy() { const hit = castAim(state.enemies.filter(e => e.userData.alive)); return hit ? findEnemyRoot(hit.object) : null; }
function sprayAt(enemy, dt) { blaster.gun.position.y = -.5 + Math.sin(performance.now() * .035) * .012; blaster.flower.rotation.z += dt * 13; for (let i = 0; i < (state.boosts.water > 0 ? 4 : 3); i++) makeWaterParticle(); collectAimedItem(); if (!enemy) { ui.crosshair.classList.remove('locked'); ui.meter.classList.remove('visible'); return; } ui.crosshair.classList.add('locked'); ui.meter.classList.add('visible'); const result = applyWater(enemy.userData, state.boosts.water > 0 ? dt * 2 : dt); ui.meterFill.style.width = `${Math.min(enemy.userData.freeze, 100)}%`; if (result.justFrozen) { announce('完全冰凍！繼續噴！'); sfx.freeze(); } if (result.shattered) shatter(enemy); }
function makeWaterParticle() { if (state.particles.length > 320) return; const big = state.boosts.water > 0 ? 1.5 : 1; const drop = new THREE.Mesh(new THREE.SphereGeometry((.12 + Math.random() * .1) * big, 7, 5), new THREE.MeshBasicMaterial({ color: 0x60eaff, transparent: true, opacity: .82 })); const origin = new THREE.Vector3(.42, -.5, -1.95).applyMatrix4(camera.matrixWorld), direction = new THREE.Vector3((Math.random() - .5) * .09 * big, (Math.random() - .5) * .09 * big, -1).normalize().applyQuaternion(camera.quaternion); drop.position.copy(origin); drop.userData.velocity = direction.multiplyScalar(18 + Math.random() * 6); drop.userData.life = .55; scene.add(drop); state.particles.push(drop); }
function shatter(enemy) { enemy.userData.alive = false; state.score += enemy.userData.points; updateHud(); announce('冰塊擊破！'); sfx.shatter(); for (let i = 0; i < 22; i++) { const shard = new THREE.Mesh(new THREE.TetrahedronGeometry(.09 + Math.random() * .15), new THREE.MeshBasicMaterial({ color: 0x9af3ff, transparent: true })); shard.position.copy(enemy.position).add(new THREE.Vector3((Math.random()-.5), .5+Math.random()*2, (Math.random()-.5))); shard.userData.velocity = new THREE.Vector3((Math.random()-.5)*5, Math.random()*5, (Math.random()-.5)*5); shard.userData.life = 1.2; scene.add(shard); state.particles.push(shard); } scene.remove(enemy); ui.meter.classList.remove('visible'); ui.crosshair.classList.remove('locked'); }
function updateParticles(dt) { state.particles = state.particles.filter(p => { p.userData.life -= dt; if (p.userData.life <= 0) { scene.remove(p); p.geometry.dispose(); p.material.dispose(); return false; } p.position.addScaledVector(p.userData.velocity, dt); if (p.geometry.type === 'TetrahedronGeometry') p.userData.velocity.y -= 6 * dt; p.material.opacity = clamp(p.userData.life, 0, .8); return true; }); }
function spawnItem() { const type = POWER_UP_TYPES[Math.floor(Math.random() * POWER_UP_TYPES.length)], color = POWER_UPS[type].color; const item = new THREE.Group(); const core = new THREE.Mesh(new THREE.OctahedronGeometry(.42), new THREE.MeshStandardMaterial({ color, emissive: color, emissiveIntensity: .7, roughness: .3 })); const halo = new THREE.Mesh(new THREE.TorusGeometry(.62, .05, 8, 28), new THREE.MeshBasicMaterial({ color })); item.add(core, halo); const light = new THREE.PointLight(color, 4, 5); item.add(light); const distance = 7 + Math.random() * 7, angle = (Math.random() - .5) * 1.6; item.position.set(Math.sin(angle) * distance, 1.5 + Math.random() * .7, camera.position.z - Math.cos(angle) * distance); Object.assign(item.userData, { itemRoot: item, type, life: 12, baseY: item.position.y, halo }); scene.add(item); state.items.push(item); announce(`出現道具：${POWER_UPS[type].label}`); sfx.itemSpawn(); }
function removeItem(item) { scene.remove(item); item.traverse(o => { o.geometry?.dispose(); o.material?.dispose(); }); state.items = state.items.filter(i => i !== item); }
function updateItems(dt, elapsed) { state.itemTimer += dt; if (state.itemTimer > 10 && state.items.length < 2) { state.itemTimer = 0; spawnItem(); } for (const item of [...state.items]) { const data = item.userData; data.life -= dt; item.rotation.y += dt * 1.6; item.position.y = data.baseY + Math.sin(elapsed * 2.5 + data.life) * .18; data.halo.rotation.x = elapsed * 2; item.visible = data.life > 3 || Math.floor(data.life * 6) % 2 === 0; if (data.life <= 0) removeItem(item); } }
function collectAimedItem() { if (!state.items.length) return; const hit = castAim(state.items); if (!hit) return; let root = hit.object; while (root && !root.userData.itemRoot) root = root.parent; if (!root) return; const type = root.userData.type; applyPowerUp(state, type, state.enemies.map(e => e.userData)); removeItem(root); announce(`獲得 ${POWER_UPS[type].label}！`); sfx.powerUp(); updateHud(); }
function updatePowerUpHud() { const active = ['water', 'slow'].filter(k => state.boosts[k] > 0).map(k => `${POWER_UPS[k].label} ${Math.ceil(state.boosts[k])}s`); ui.powerUp.textContent = active.join('　'); ui.powerUp.classList.toggle('visible', active.length > 0); }
function updateHud() { ui.healthBar.style.width = `${state.health}%`; ui.healthText.textContent = Math.ceil(state.health); ui.score.textContent = state.score; ui.healthBar.style.background = state.health < 35 ? '#ff4d4d' : 'linear-gradient(90deg, #37e0c1, #b6f25a)'; }
function hitPlayer() { ui.flash.classList.add('show'); announce('被殭屍碰到了！'); sfx.hurt(); setTimeout(() => ui.flash.classList.remove('show'), 180); }
function announce(text) { ui.message.textContent = text; ui.message.classList.add('show'); clearTimeout(announce.timer); announce.timer = setTimeout(() => ui.message.classList.remove('show'), 950); }
function gameOver() { state.running = false; state.spraying = false; setSpraying(false); sfx.gameOver(); ui.panel.classList.remove('hidden'); ui.panel.querySelector('h1').textContent = '守不住了！'; ui.panel.querySelector('p').textContent = `你得到 ${state.score} 分，再試一次！`; ui.start.textContent = '重新出發'; }
const deviceEuler = new THREE.Euler(), deviceQuat = new THREE.Quaternion(), screenQuat = new THREE.Quaternion(), backCameraQuat = new THREE.Quaternion(-Math.sqrt(.5), 0, 0, Math.sqrt(.5)), zAxis = new THREE.Vector3(0, 0, 1), lookEuler = new THREE.Euler(0, 0, 0, 'YXZ');
function screenAngle() { return THREE.MathUtils.degToRad(screen.orientation?.angle ?? window.orientation ?? 0); }
// 把手機的方向換算成「手機背面鏡頭朝向」的左右 (yaw) 與上下 (pitch)，直拿、橫拿都正確
function deviceLook(alpha, beta, gamma, orient) { const d = THREE.MathUtils.degToRad; deviceEuler.set(d(beta), d(alpha), -d(gamma), 'YXZ'); deviceQuat.setFromEuler(deviceEuler).multiply(backCameraQuat).multiply(screenQuat.setFromAxisAngle(zAxis, -orient)); lookEuler.setFromQuaternion(deviceQuat, 'YXZ'); return { yaw: lookEuler.y, pitch: lookEuler.x }; }
function handleOrientation(event) { if (!state.running || event.alpha == null) return; const look = deviceLook(event.alpha, event.beta ?? 90, event.gamma ?? 0, screenAngle()); if (state.baseYaw == null) { state.baseYaw = look.yaw; state.basePitch = look.pitch; } // 開始時手機怎麼拿，就當作正前方
  state.yaw = clamp(relativeAngle(look.yaw, state.baseYaw) * GYRO_SENSITIVITY, -MAX_AIM_YAW, MAX_AIM_YAW); state.pitch = clamp((look.pitch - state.basePitch) * GYRO_SENSITIVITY, MIN_AIM_PITCH, MAX_AIM_PITCH); }
async function startGame() { initAudio(); sfx.start(); if (typeof DeviceOrientationEvent !== 'undefined' && typeof DeviceOrientationEvent.requestPermission === 'function') { try { const permission = await DeviceOrientationEvent.requestPermission(); if (permission !== 'granted') announce('未允許感測器，可用手指拖曳視角'); } catch { announce('可用手指拖曳視角'); } } state.enemies.forEach(e => scene.remove(e)); state.enemies = []; [...state.items].forEach(removeItem); state.itemTimer = 5; state.boosts = { water: 0, slow: 0 }; Object.assign(state, { running: true, spraying: false, health: 100, score: 0, wave: 0, spawnTimer: 0, baseYaw: null, basePitch: null, groanTimer: 3, yaw: 0, pitch: 0 }); camera.rotation.set(0, 0, 0); ui.panel.classList.add('hidden'); updateHud(); spawnWave(); clock.start(); }
function loop() { requestAnimationFrame(loop); const dt = Math.min(clock.getDelta(), .05), elapsed = clock.elapsedTime; updateScene(performance.now() / 1000); setSpraying(state.running && state.spraying, state.boosts.water > 0); if (state.running) { camera.rotation.y = stepAim(camera.rotation.y, state.yaw, dt, AIM_SMOOTHING, AIM_MAX_SPEED); camera.rotation.x = stepAim(camera.rotation.x, state.pitch, dt, AIM_SMOOTHING, AIM_MAX_SPEED); tickBoosts(state.boosts, dt); updatePowerUpHud(); const enemy = targetEnemy(); if (state.spraying) sprayAt(enemy, dt); else { ui.crosshair.classList.toggle('locked', !!enemy); ui.meter.classList.remove('visible'); } const enemyDt = state.boosts.slow > 0 ? dt * .4 : dt; state.enemies.forEach(e => updateEnemy(e, enemyDt, elapsed)); updateItems(dt, elapsed); updateParticles(dt); updateGroans(dt); if (state.enemies.every(e => !e.userData.alive)) { state.spawnTimer += dt; if (state.spawnTimer > 1.5) { state.spawnTimer = 0; spawnWave(); } } } renderer.render(scene, camera); }
function updateGroans(dt) { state.groanTimer -= dt; if (state.groanTimer > 0) return; state.groanTimer = 2.5 + Math.random() * 3; const alive = state.enemies.filter(e => e.userData.alive && e.userData.freeze < 100); if (alive.length) sfx.groan(alive[Math.floor(Math.random() * alive.length)].userData.distance); }
function renderMute() { ui.mute.textContent = isMuted() ? '🔇' : '🔊'; ui.mute.setAttribute('aria-label', isMuted() ? '開啟音效' : '關閉音效'); }
function resize() { renderer.setSize(innerWidth, innerHeight, false); camera.aspect = innerWidth / innerHeight; camera.updateProjectionMatrix(); }
window.addEventListener('resize', resize); resize(); window.addEventListener('deviceorientation', handleOrientation, true); screen.orientation?.addEventListener?.('change', () => { state.baseYaw = null; }); ui.start.addEventListener('click', startGame); ui.mute.addEventListener('click', () => { initAudio(); toggleMute(); renderMute(); }); renderMute();
canvas.addEventListener('pointerdown', e => { if (!state.running) return; state.spraying = true; state.dragging = true; state.dragX = e.clientX; state.dragY = e.clientY; canvas.setPointerCapture?.(e.pointerId); });
canvas.addEventListener('pointermove', e => { if (!state.dragging || e.pointerType !== 'mouse') return; state.yaw = clamp(state.yaw - (e.clientX - state.dragX) * .0018, -MAX_AIM_YAW, MAX_AIM_YAW); state.pitch = clamp(state.pitch - (e.clientY - state.dragY) * .0014, MIN_AIM_PITCH, MAX_AIM_PITCH); state.dragX = e.clientX; state.dragY = e.clientY; });
window.addEventListener('pointerup', () => { state.spraying = false; state.dragging = false; }); window.addEventListener('pointercancel', () => { state.spraying = false; state.dragging = false; }); addEventListener('contextmenu', e => e.preventDefault()); loop();
